### ISSUE TITLE
Unknown layer type 'SubP'

### ISSUE THREAD

**Issue by AtenaKid** [cszn/FFDNet#1]
Hi there, 

I just run the demo_awgn_gray and got this error

Demo_AWGN_Gray
Error using vl_simplenn (line 377)
Unknown layer type 'SubP'.
Error in Demo_AWGN_Gray (line 88)
res    =    vl_simplenn(net,input,[],[],'conserveMemory',true,'mode','test'); 

Any idea to fix it?

Best regards,

**Comment by cszn** [comment]
Use [`vl_simplenn.m`](https://github.com/cszn/FFDNet/blob/master/utilities/vl_simplenn.m) and  [SubP layer](https://github.com/cszn/FFDNet/blob/master/utilities/vl_nnSubP.m) from [`utilities`](https://github.com/cszn/FFDNet/tree/master/utilities) folder.
