### ISSUE TITLE
Request for test code

### ISSUE THREAD

**Issue by terryoo** [cszn/FFDNet#10]
Hi @ @cszn
This project and paper are great. 
I want to test spatially variant noise images with noise level mask (Fig5 in arxiv paper), can you share me the test  codes? 
Thanks a lot

**Comment by cszn** [comment]
See [this](https://github.com/cszn/FFDNet/blob/master/Demo_AWGN_spatially_variant_noise.m).

**Comment by terryoo** [comment]
Thank a lot!!
Have a good day
