### ISSUE TITLE
Elements in noise level map

### ISSUE THREAD

**Issue by JacksonZyy** [cszn/FFDNet#24]
Hi, 

For AWGN images, you mention in the paper that the noise level map should take uniform element \sigma.
May I know why the noise level map is set in this way for AWGN?
And is it ok to denoise AWGN image with non-uniform noise level map?

Thanks,
Yuyi

**Comment by cszn** [comment]
Absolutely, non-uniform noise level map is a better choice. You may read the paper again.

**Comment by JacksonZyy** [comment]
> Absolutely, non-uniform noise level map is a better choice. You may read the paper again.

Hi,

Thanks for replying.
It is indeed mentioned in the paper that a non-uniform map is used for spatially VARIANT noise.
But if non-uniform map is always the best choice like you said, why don't you use it also for spatially INVARIANT noise like AWGN?

Thanks,
Yuyi

**Comment by cszn** [comment]
I mean non-uniform noise level map is a better choice for images with real AWGN.
