### ISSUE TITLE
comparison with RBDN

### ISSUE THREAD

**Issue by TouqeerAhmad** [cszn/FFDNet#4]
Hello, it is more of a question than an issue. 
I was reading recent papers on image denoising and have read DnCNN and FFDNet papers. I was curious as to why you have not compared FFDNet with RBDN -- it was mentioned in related work in FFDNet. Is the comparison going to be there in final version of FFDNet -- as RBDN is also quite recent. 

Thanks, 
Touqeer

**Comment by cszn** [comment]
There are two different settings for additive white Gaussian denoising. The difference is whether clip the noisy input into [0, 255] or not. In DnCNN, the noisy input is not clipped into [0, 255], however, RBDN does the quantization. It is unfair to compare those two models with different training settings. Actually, the noise is not AWGN with zero mean any more after the quantization. 

In the revised FFDNet, we will add the comparison with additional models.

**Comment by TouqeerAhmad** [comment]
makes sense, thank you!

**Comment by TouqeerAhmad** [comment]
@cszn Hello, I was wondering if you have trained  FFDNet available in another format e.g. Tensorflow, Caffe or pytorch. I was able to get pytorch implementation of DnCNN but not of FFDNet. 

Or otherwise, if you know of any reliable way to convert the learned model to different frameworks. MatConvNet can not be used unless you have Matlab, which unfortunately I don't have access to right now.

**Comment by cszn** [comment]
Sorry, I am not familiar with pytorch.

**Comment by cszn** [comment]
New models for noisy image with clipping setting are added.
