### ISSUE TITLE
The most interesting is how to work with different Noise Level 

### ISSUE THREAD

**Issue by fsword73** [cszn/FFDNet#6]
The method could be framework for other image processing like  Demosaic, HDRNet and Learning to see in the dark... 

一个统一的处理架构针对几乎连续的场景，这是Deep Learning可以真正工业化的方法。 
赞！

This is not an issue.  Appciate your innovation!

**Comment by RoyiAvital** [comment]
I would say another interesting aspect would be how to deal with Spatially Correlated Noise.

Usually it is done in a Multi Scale Approach.
What would be the best way to do it in FFDNet?

**Comment by RoyiAvital** [comment]
Why is it closed?

**Comment by cszn** [comment]
I have answered you via the email.
